### ISSUE TITLE
Windows: ensuring an interface does not reload?

### ISSUE THREAD

**Issue by chunkdaddy** [target/network_interfaces_v2-cookbook#22]
First off, i'd like to say I think this cookbook is awesome, and so far works like a charm!  The only thing i've encountered is how to properly disable the immediate reload of the config with Windows 

I'm using "reload false" in my recipe, but the interface is still configured (perfectly, to be sure) AND reloaded, where I would like the configuration NOT to be reloaded until the host is rebooted, more than likely by another program, which would need to maintain connectivity to the host.

Again, love the cookbook!

```
network_interface 'eth0' do
    reload false
    ddns true
    netbios true
    bootproto 'static'
    hw_address node['blah']['networking']['MAC']
    address node['blah']['networking']['IP']
    netmask node['blah']['networking']['netmask']
    gateway node['blah']['networking']['gateway']
    dns node['blah']['networking']['nameservers']
    dns_domain node['blah']['networking']['dnssearch']
end
```

**Comment by jmccann** [comment]
Could you provide the Chef output regarding the interface that shouldn't reload but is reloading?

I'm trying to determine if Chef is reloading the interface, which would cause output of `Reloading eth0` to be shown, or if something else is triggering windows to automatically do a reload.

**Comment by chunkdaddy** [comment]
![screen shot 2016-04-22 at 12 23 41 pm](https://cloud.githubusercontent.com/assets/3299175/14748894/40dae3e0-088a-11e6-80f2-f564f6961f00.png)

Apologies for the screen shot and thanks for the reply!

**Comment by jmccann** [comment]
I'll have to look into this more.  It doesn't show that it's reloading the interface.  Maybe setting a parameter causes windows to reload it automatically.  I'm not sure.

I'll try to look into it as I find time ... but I'm really busy so it may be a while.  If you figure something out though let me know!  😉

**Comment by chunkdaddy** [comment]
So, I noticed in both the CHANGELOG and my log output that there was a DHCP release added, and that release is not part of the reload process, but separate.
Perhaps it's the release of the DHCP address that's causing the issue i'm seeing?  As far as i can tell this logic would prevent the reload from happening:
`reload if new_resource.updated_by_last_action? && new_resource.reload`
because the second condition should always be false courtesy of the attribute.  

Is there a way to control the releasing of the DHCP address?  I would consider that to be a "reload", at least for Windows purposes, in that when the NIC is reconfigured (regardless if it's "reloaded" or not after) with a static address and it's DHCP address has already been released, what is expected to be providing network connectivity at that point?

Thanks!

**Comment by chunkdaddy** [comment]
For context, we provision systems on 1 VLAN and "flip" the system to it's run VLAN after, and the system needs to maintain network connectivity to the provisioner during the process.  With linux, it's easily accomplished by editing the ifcfg files but not performing a reload, and we're looking to replicate that functionality in Windows.
