### ISSUE TITLE
Readme inconsistency: RHEL 7.x supported or semi-supported

### ISSUE THREAD

**Issue by mathwizard1232** [target/network_interfaces_v2-cookbook#41]
Title is basically the entirety of the issue. Just looking at the readme, RHEL 7.x is listed both under supported and semi-supported. Presumably it's one or the other, but I don't know if it's being upgraded to supported or downgraded to semi-supported for some reason.

**Comment by mathwizard1232** [comment]
My guess is it should be supported and removed from semi-supported based on this issue: https://github.com/target/network_interfaces_v2-cookbook/issues/7

**Comment by jmccann** [comment]
Yes, it should be supported.  A PR with update to README would be welcome. 😄
