### ISSUE TITLE
support action :remove

### ISSUE THREAD

**Issue by tommynsong** [target/network_interfaces_v2-cookbook#8]
would like to know if you plan to implement the action

**Comment by jmccann** [comment]
What would the difference be for :remove vs :disable (proposed in #9?)

**Comment by tommynsong** [comment]
:remove would bring the interface down and remove the interface configuration while :disable would only down the interface.

**Comment by jmccann** [comment]
Closing this issue as I don't plan to work on it though PRs for this feature would be gladly reviewed.
